sudo: true

services:
  - docker

env:
  global:
    secure: r/NXfTzS5KxvrpuzTmygyPrbqvC0M7pgz91dZhC3Wy7yXDuHJFK1gM7YpsqRWuPoez0HMK3B5VrFMHuzuEzKxsjiFzcWCMob372ZiDJdZN0WibtpTynkZPjm3j0RCF8nDLadDPyMWSSYegC95ZSKP9NuzMF46x06q9LgGYeAF7OsHN10OjE4YsCGkmTgyQpNPWA1MAPjYp2Ue0joS7XYXMIxJBipRjZqRgOxPKyBh4G8wHGz7/4SK6iKXb75tfqREwtniPHJ8KzTbz4kyG/OMkJqlApRr+hojzGHynA/7zG5Jw5fpC/9vSBU0WpuvjSZYpH7muZ0Rpq/jcucPlLz975+t0J2UgEn6cjGGHS/KPIllm9ePTHSkEb1rAdpO7xeYsiWfIIohwGTk5gWkr9G0qTjkmILdAjk96NixJz+1v6vS37eXN9v04xo0jkl96MZg9OTRjJ3pSEcyJfKl1J+NNLjuM0dop544KBFHsGCS35ESVIoBOnfYChptah/Q4ucuuWK1jObkSigJlE02LVh7wQi49Dg2/OERyBVFgObFqEHwwW4SbuIQ5aQmMoNXvwaBIWSxyGDQOzBmhsHtYS4F0SWRW/ZHjM0rqfIBC8I3HCurTISxwnzEO8PLU4SmrMEWQtKkCQgnScKDjKKex0OZIba9Hew37nkvJEMqAli4A0=

script:
  - export TAG=`git describe --tags`;
  - docker build no-factor-auth -t heappurple.azurecr.io/complete/no-factor-auth:$TAG;

before_deploy:
  - echo $DOCKER_PASSWORD | docker login heappurple.azurecr.io -u heappurple --password-stdin
  - docker build --build-arg TAG=$TAG -f Docker.dist -t dist
  - docker container rm bins || true
  - docker create --name bins bins
  - docker cp bins:/code/no-factor-auth.linux .
  - docker cp bins:/code/no-factor-auth.exe .
  - docker cp bins:/code/no-factor-auth.darwin .

deploy:
  - provider: script
    script: docker push heappurple.azurecr.io/complete/no-factor-auth:$TAG
    on:
      tags: true
  - provider: releases
    api_key: $GH_TOKEN
    overwrite: true
    skip_cleanup: true
    file:
      - no-factor-auth.linux
      - no-factor-auth.exe
      - no-factor-auth.darwin
    on:
      tags: true
